### ISSUE TITLE
Use of reserved identifiers

### ISSUE THREAD

**Issue by jason-watkins** [nasa/PolyCARP#2]
I notice several instances where identifiers of the form _{capital letter} are used (e.g. [here](https://github.com/nasa/PolyCARP/blob/4f7d209a98c253f663920b80809cb8560ddc5354/C%2B%2B/include/Constants.h#L25)). These identifiers are [reserved](https://en.cppreference.com/w/cpp/language/identifiers) by the C++ standard and using them is undefined behavior.

I'm not sure this causes any issues in practice, but undefined behavior in safety critical software can never be a good thing, right?

**Comment by cesaramh** [comment]
Done.
